### ISSUE TITLE
random ascii codec error

### ISSUE THREAD

**Issue by davidak** [davidak/random-vcard-generator#13]
with python 2.7 and pypy

```
$ python --version
Python 2.7.9

$ vcardgen -c 3 Kontakt.vcf
[###.......] |  33.3% | VCard: 1 / 3 | Time: 0.0s | ETA: 0.0s                  Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/vcardgen", line 9, in <module>
    load_entry_point('vcardgen==0.8.2', 'console_scripts', 'vcardgen')()
  File "build/bdist.linux-x86_64/egg/vcardgen/main.py", line 92, in main
  File "build/bdist.linux-x86_64/egg/vcardgen/main.py", line 79, in generate_vcard
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 78: ordinal not in range(128)
```

```
$ python --version
Python 2.7.8 (10f1b29a2bd2, Feb 02 2015, 21:22:43)
[PyPy 2.5.0 with GCC 4.6.3]

$ vcardgen -c 3 Kontakt.vcf
[###.......] |  33.3% | VCard: 1 / 3 | Time: 0.0s | ETA: 0.0s                  Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/home/travis/virtualenv/pypy-2.5.0/bin/vcardgen", line 9, in <module>
    load_entry_point('vcardgen==0.8.2', 'console_scripts', 'vcardgen')()
  File "build/bdist.linux-x86_64/egg/vcardgen/main.py", line 92, in main
    output += generate_vcard()
  File "build/bdist.linux-x86_64/egg/vcardgen/main.py", line 45, in generate_vcard
    _s += "FN:{}\n".format(_p.name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 9: ordinal not in range(128)
```

**Comment by davidak** [comment]
the problem above was fixed by https://github.com/davidak/random-vcard-generator/commit/e4064404c94f2d476f803d9472bfd643d538e2b0

**Comment by davidak** [comment]
```
imac:random-vcard-generator davidak$ python -m vcardgen.main > test
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/davidak/code/random-vcard-generator/vcardgen/main.py", line 105, in <module>
    print(generate_vcard())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 329: ordinal not in range(128)
```
