### ISSUE TITLE
File write problem with lots of vcards

### ISSUE THREAD

**Issue by davidak** [davidak/random-vcard-generator#14]
```
unibook:test davidak$ vcardgen -c 10000000 10000000.vcf
[##########] | 100.0% | VCard: 10000000 / 10000000 | Time: 1h27min13s | ETA: --

Traceback (most recent call last):
  File "/usr/local/bin/vcardgen", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/vcardgen/main.py", line 103, in main
    f.write(output)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 718, in write
    return self.writer.write(data)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 377, in write
    self.stream.write(data)
OSError: [Errno 22] Invalid argument
```

6000000 OK
7000000 Error

maybe predict needed disk space and exit if not available. i think this was not a ram problem since the generation was completed.

http://stackoverflow.com/a/2372171/2611995

>Batching the writes into groups of 500 did indeed speed up the writes significantly.
http://stackoverflow.com/a/4985439/2611995

maybe a bug: https://bugs.python.org/issue24658

**Comment by davidak** [comment]
performance:

```
imac:random-vcard-generator davidak$ time python -m vcardgen.main -c 10000 >test

real	0m9.492s
user	0m7.072s
sys	0m1.254s
imac:random-vcard-generator davidak$ time python -m vcardgen.main -c 10000 -f test
[##########] | 100.0% | VCard: 10000 / 10000 | Time: 28.9s | ETA: --


real	0m29.046s
user	0m16.658s
sys	0m9.232s
```

**Comment by davidak** [comment]
nach https://github.com/davidak/random-vcard-generator/commit/ce646dcccebc80915f1e8dcf3e25360d80b420a2 (3 fache geschwindigkeit)

```
imac:random-vcard-generator davidak$ time python -m vcardgen.main -c 10000 -f test
[##########] | 100.0% | VCard: 10000 / 10000 | Time: 11.2s | ETA: --


real	0m11.358s
user	0m7.733s
sys	0m1.310s
```

**Comment by davidak** [comment]
also fixed in https://github.com/davidak/random-vcard-generator/commit/ce646dcccebc80915f1e8dcf3e25360d80b420a2

**Comment by davidak** [comment]
test again without BOINC running:

```
imac:random-vcard-generator davidak$ time python -m vcardgen.main -c 10000 -f test
[##########] | 100.0% | VCard: 10000 / 10000 | Time: 5.1s | ETA: --


real	0m5.443s
user	0m4.349s
sys	0m0.803s
```
